name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  image_name: factorio-docker-watchdog

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository 
      uses: actions/checkout@v3
    - name: Docker Login
      run: echo -n ${REGISTRY_PASSWORD} | docker login -u ${REGISTRY_USERNAME} --password-stdin ${REGISTRY_NAME}
      env:
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
    - name: Build and push the Docker image
      run: |
        IMAGE_VERSION=$(date +%Y%m%d-%H%M%S)
        docker run --privileged --rm tonistiigi/binfmt --install arm64
        docker run --privileged --rm tonistiigi/binfmt
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 \
          -t ${REGISTRY_NAME}/${image_name}:${IMAGE_VERSION} \
          -t ${REGISTRY_NAME}/${image_name}:latest \
          --push \
          .
      env:
        REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}